name: Build and Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            extension: ""
          - os: windows-latest
            extension: ".exe"
          - os: macos-latest
            extension: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Build the binary
        run: go build -o myapp${{ matrix.extension }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-binary-${{ matrix.os }}
          path: myapp${{ matrix.extension }}
